GoalApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  resource :session
  resources :goals
end

GoalApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GoalApp/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint(8)        not null, primary key
#  user_id    :string           not null
#  state      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string
#

class Goal < ApplicationRecord
  STATES = %w(public private)
  
  validates :title, :user_id, :state, presence: true
  
  belongs_to :user,
    foreign_key: :user_id,
    class_name: :User
    
  def self.states
    STATES.dup
  end
end

GoalApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :session_token, :email, uniqueness:true
  
  after_initialize :ensure_session_token
  
  has_many :goals,
    foreign_key: :user_id,
    class_name: :Goal
  
  attr_reader :password
  
  def self.find_by_credentials (email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end
  
  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
  def generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
  
  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end
end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def logged_in?
    !!current_user
  end
  
  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logout!
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end
end

GoalApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
    render :index
  end
  
  def new
    @goal = Goal.new
    render :new
  end
  
  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to user_url(@goal.user_id)
    else
      flash[:errors] = "Wrong username or password"
      render new_session_url
    end
  end
  
  def destroy
    @goal = Goal.find(params[:id])
    
    if @goal.delete
      redirect_to goals_url
    else
      flash[:errors] = @goal.errors.full_messages
      redirect_to goals_url  
    end
  end
  
  private
  
  def goal_params
    params.require(:goal).permit(:title, :user_id, :state)
  end
end

GoalApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password],
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Wrong username or password"
      @user = User.new
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end  
end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def index
    @users = User.all
    render :index
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def edit
    @user = User.find(params[:id])
    render :edit
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash[:errors] = @users.errors.full_messages
      redirect_to edit_user_url(@user)
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    
    if @user.delete
      redirect_to users_url
    else
      flash[:errors] = @users.errors.full_messages
      redirect_to edit_user_url(@user)
    end
  end
    
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' 
    name='authenticity_token' 
    value='#{form_authenticity_token}'>".html_safe
  end
  
  def logout
    "<form action='#{session_url}' method='post'>
      #{auth_token}
      <input type='hidden' name='_method' value='delete'>
      <input type='submit' name='submit' value='Logout'>
    </form>".html_safe
  end
  
  def delete_user(user)
    "<form action='#{user_url(user)}' method='post'>
      #{auth_token}
      <input type='hidden' name='_method' value='delete'>
      <input type='submit' name='submit' value='Delete User'>
    </form>".html_safe
  end
  
  def delete_goal(goal)
    "<form action='#{goal_url(goal)}' method='post'>
      #{auth_token}
      <input type='hidden' name='_method' value='delete'>
      <input type='submit' name='submit' value='Delete Goal'>
    </form>".html_safe
  end
  
end

GoalApp/app/views/goals/_form.html.erb
<% if type == :new %>
  <% button_msg = "Create new goal" %>
  <% action_url = goals_url %>
  <% headed_line_text = "Create a new goal!" %>
<% elsif type == :edit %>
  <% button_msg = "Edit this goal" %>
  <% action_url = goal_url(goal) %>
  <% headed_line_text = "Edit this goal" %>
<% end %>

<h2> <%= headed_line_text %></h2>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
  <label for="title">Title:</label>
  <input type="text" id='title' name="goal[title]" value="<%= goal.title %>">
  <br>
  
  <label for=""></label>
  <select class="" name="goal[user_id]">
    <% User.all.each do |user| %>
      <option value="<%= user.id %>"  <%= 'selected' if goal.user_id = user.id %>>
         <%= user.email %></option>
    <% end %>
  </select>
  <br>
  
  <label for="state">State:</label><br>
  <% Goal.states.each do|state| %>
    <input type="radio" id='state' name="goal[state]" 
      value="<%= state %>"  <%= 'checked' if goal.state == state %> ><%= state %>
  <% end %>
  <br>
  
  <input type="submit" name="submit" value="<%=button_msg %>">
</form>

GoalApp/app/views/goals/edit.html.erb
<%= render 'form', type: :edit, goal: @goal %>

GoalApp/app/views/goals/index.html.erb
<h1>ALL GOALS</h1>

<a href=" <%= new_goal_url %>"> Add a new goal!</a><br>

<% @goals.each do |goal| %>
  <% if goal.state == 'public' %>
    <li><%= goal.title %></li><br>
    <a href=" <%= edit_goal_url(goal) %>">Edit goal </a>
    <%= delete_goal(goal) %>
  <% end %>
<% end %>

GoalApp/app/views/goals/new.html.erb
<%= render 'form', type: :new, goal: @goal %>

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <%= render '/shared/errors', errors: flash[:errors] %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

GoalApp/app/views/shared/_errors.html.erb
<% errors.each do |error| %>
  <li> <%= error %></li>
<% end %>

GoalApp/app/views/users/_form.html.erb
<% if type == :signup %>
  <% button_msg = "Sign Up" %>
  <% action_url = users_url %>
  <% headed_line_text = "Sign Up for an account, below:" %>
<% elsif type == :edit %>
  <% button_msg = "Edit User" %>
  <% action_url = user_url(user) %>
  <% headed_line_text = "Edit your username or password below:" %>
<% elsif type == :signin %>
  <% button_msg = "Sign In" %>
  <% action_url = session_url%>
  <% headed_line_text = "Sign In below:" %>
<% end %>

<h2> <%= headed_line_text %></h2>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
  <label for="email">Email:</label>
  <input type="email" id='email' name="user[email]" value="<%= user.email %>">
  <br>
  
  <label for="password">Password:</label>
  <input type="password" id='password' name="user[password]">
  <br>
  
  <input type="submit" name="submit" value="<%=button_msg %>">
</form>

GoalApp/app/views/users/edit.html.erb
<%= render 'form', type: :edit, user: @user %>

GoalApp/app/views/users/index.html.erb
<% @users.each do |user| %>
  <li> <%= user.email %></li>
<% end %>

GoalApp/app/views/users/new.html.erb
<%= render 'form', type: :signup, user: @user %>

GoalApp/app/views/users/show.html.erb
<h1>Welcome <%=@user.email%></h1> 

<%= delete_user(@user) %>

<%= logout %>